[deps]
DiffEqJump = "c894b116-72e5-5b58-be3c-e6d8d4ac2b12"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLTutorials = "30cb0354-2223-46a9-baa0-41bdcfbe0178"

[compat]
DiffEqJump = "7.3"
LightGraphs = "1.3.5"
Plots = "1.20.1"
SciMLTutorials = "0.9, 1"
