# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
enable-beta-ecosystems: true # Julia ecosystem
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
      - "/test"
    schedule:
      interval: "daily"
    groups:
      all-julia-packages:
        patterns:
          - "*"
