include: https://raw.githubusercontent.com/SciML/RebuildAction/master/rebuild.yml
variables:
  CONTENT_DIR: tutorials
  EXCLUDE: exercises/02-workshop_solutions, models/06-pendulum_bayesian_inference
  GITHUB_REPOSITORY: SciML/DiffEqTutorials.jl
  GPU_TAG: nvidia-benchmark
  NEEDS_GPU: advanced/01-beeler_reuter
  TAGS: nvidia-benchmark
