name = "DiffEqTutorials"
uuid = "6d1b261a-3be8-11e9-3f2f-0b112a9a8436"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.5.0"

[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
ArbNumerics = "7e558dbc-694d-5a72-987c-6f4ebed21442"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
DecFP = "55939f99-70c6-5e9b-8bb0-5071ed7d61fd"
Decimals = "abce61dc-4473-55a0-ba07-351d65e31d42"
DiffEqBayes = "ebbdde9d-f333-5424-9be2-dbf1e9acfb5e"
DiffEqBiological = "eb300fae-53e8-50a0-950c-e21f52c2b7e0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
DiffEqParamEstim = "1130ab10-4a5a-5621-a13d-e4788d82bd4c"
DiffEqPhysics = "055956cb-9e8b-5191-98cc-73ae4a59e68a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
SparsityDetection = "684fba80-ace3-11e9-3d08-3bc7ed6f96df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
AlgebraicMultigrid = "0.2"
ArbNumerics = "1.0"
BenchmarkTools = "0.4, 0.5"
CUDAnative = "2.5, 3.0"
Cairo = "0.8, 1.0"
CuArrays = "1.4, 2.0"
DecFP = "0.4"
Decimals = "0.4"
DiffEqBayes = "2.1"
DiffEqBiological = "4.0"
DiffEqCallbacks = "2.9"
DiffEqDevTools = "2.15"
DiffEqOperators = "4.3"
DiffEqParamEstim = "1.8"
DiffEqPhysics = "3.2"
DifferentialEquations = "6.8"
Distributions = "0.21, 0.22, 0.23"
DoubleFloats = "0.9, 1.0"
ForwardDiff = "0.10"
IJulia = "1.20"
Latexify = "0.12, 0.13"
MCMCChains = "3.0"
Measurements = "2.1"
ModelingToolkit = "0.9, 0.10, 1.0"
NLsolve = "4.2"
Optim = "0.19, 0.20"
OrdinaryDiffEq = "5.23"
ParameterizedFunctions = "4.2, 5.0"
Plots = "0.27, 0.28, 0.29"
PyPlot = "2.8"
RecursiveArrayTools = "1,2"
SparseDiffTools = "0.10, 1.0"
SparsityDetection = "0.1, 0.2"
StaticArrays = "0.10, 0.11, 0.12"
StatsPlots = "0.12, 0.13, 0.14"
Sundials = "3.8"
Unitful = "0.17, 0.18, 1.0"
Weave = "0.9"
julia = "1"
