name = "SciMLTutorials"
uuid = "30cb0354-2223-46a9-baa0-41bdcfbe0178"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.9.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
IJulia = "1.20"
Plots = "1.6"
Weave = "0.10"
julia = "1.4"
