[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
DiffEqGPU = "071ae1c0-96b5-11e9-1965-c90190d839ea"
DiffEqSensitivity = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
DiffEqUncertainty = "ef61062a-5684-51dc-bb67-a0fcdec5c97d"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Quadrature = "67601950-bd08-11e9-3c89-fd23fb4432d2"
SciMLTutorials = "30cb0354-2223-46a9-baa0-41bdcfbe0178"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
BenchmarkTools = "0.5, 0.6, 0.7, 1.0"
Cuba = "2.1"
DiffEqGPU = "1.5"
DiffEqSensitivity = "6.28"
DiffEqUncertainty = "1.5"
DifferentialEquations = "6.15"
Distributions = "0.23, 0.24, 0.25"
ForwardDiff = "0.10"
KernelDensity = "0.6"
MCMCChains = "4.4"
NLopt = "0.6"
OrdinaryDiffEq = "5.42"
Plots = "1.5"
Quadrature = "1.3"
SciMLTutorials = "0.9"
StatsPlots = "0.14"
Turing = "0.15, 0.16"
