[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
DiffEqGPU = "071ae1c0-96b5-11e9-1965-c90190d839ea"
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
SparsityDetection = "684fba80-ace3-11e9-3d08-3bc7ed6f96df"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
AlgebraicMultigrid = "0.3, 0.4"
BenchmarkTools = "0.5, 0.6"
DiffEqDevTools = "2.22"
DiffEqFlux = "1.16"
DiffEqGPU = "1.3"
DiffEqOperators = "4.10"
DifferentialEquations = "6"
Flux = "0.10, 0.11"
Optim = "0.21, 0.22, 1.0"
Plots = "1.5"
SparseDiffTools = "1.9"
SparsityDetection = "0.3"
Sundials = "4.2"
