[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NeuralNetDiffEq = "8faf48c0-8b73-11e9-0e63-2155955bfa4d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
SparsityDetection = "684fba80-ace3-11e9-3d08-3bc7ed6f96df"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
AlgebraicMultigrid = "0.3, 0.4"
BenchmarkTools = "0.5, 0.6"
CUDAnative = "3.1"
CuArrays = "2.2"
DiffEqOperators = "4.10"
DifferentialEquations = "6.14"
Flux = "0.10, 0.11"
ModelingToolkit = "3.10, 4.0, 5.0"
NLsolve = "4.4"
NeuralNetDiffEq = "1.6"
OrdinaryDiffEq = "5.41"
Plots = "1.4"
SparseDiffTools = "1.9"
SparsityDetection = "0.3"
StochasticDiffEq = "6.23"
Sundials = "4.2"
