name: Rebuild Content
on:
  schedule:
    - cron: 0 0 */3 * *
  issue_comment:
    types:
      - created
  push:
env:
  BUILDKITE_PROJECT: scimltutorials-dot-jl
  BUILDKITE_TOKEN: ${{ secrets.BUILDKITE_TOKEN }}
jobs:
  Rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: SciML/RebuildAction@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
