name: Rebuild Content
on:
  schedule:
    - cron: 0 0 */3 * *
  issue_comment:
    types:
      - created
  push:
  status:
env:
  GITLAB_PROJECT: ${{ secrets.GITLAB_PROJECT }}
  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
jobs:
  Rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: SciML/RebuildAction@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
